### ISSUE TITLE
Make player messages less verbose

### ISSUE THREAD

**Issue by DoNotSpamPls** [games647/ChangeSkin#120]
![](https://bitcoin.is-serious.business/991a26.png)

In my opinion, most users wouldn't care that "their UUID was successfully resolved" or that "their skin is downloading", they just want a skin. I see the point in more verbose messages, but I don't think it should be *that* verbose, at least for players. Maybe the extra messages could be moved to a debug option in the config.

**Comment by games647** [comment]
Good point. I think you're right. Maybe it would be enough to just down tear it down to two messages like this:

1. UUID successful resolved and skin is now downloading
2. You received your new skin

If an error occurs it could then be displayed instead of one of those messages.

As a temporarily solution it's possible for the user to edit the messages file and clear the contents inside the quotes. ChangeSkin will then ignore it.
