### ISSUE TITLE
Skinupdate doesn't work

### ISSUE THREAD

**Issue by andramil** [games647/ChangeSkin#183]
[//]: # (Lines in this format are considered as comments and will not be displayed.)
[//]: #
[//]: # (Before reporting an issue make sure you are running the latest build and checked for duplicate issues!)

### What behaviour is observed:
[//]: # (What happened?)
Command /skinupdate doen't work. Skins doesn't update on my serwer. It worked like 4 days ago, and with no change on server, stopped.

### What behaviour is expected:
[//]: # (What did you expect?)
Skins should update to mojang database after /skinupdate

### Steps/models to reproduce:
[//]: # (The actions that cause the issue. Please explain it in detail)
Type /skinupdate or /skinupdate nick - no changes
### Environment description
[//]: # (Standalone server/Bungeecord network with version and build number, SQLite/MySQL, ...)
Bungeecord server 
Spigot 1.8-1.15.2

### Plugin version or build number:
[//]: # (Don't write latest or the build number with #. #Number is used to reference to other tickets.)
[//]: # (This can be found by running `/version plugin-name`.)
Build 223
### Error Log:
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of the error (if any)

https://code.skript.pl/YJNFVZv4

### Configuration:
[//]: # (Remember to delete any sensitive data)
[Hastebin](https://hastebin.com/) / [Gist](https://gist.github.com/) link of your config.yml file 

https://code.skript.pl/rYgq91QW

**Comment by Nextopi** [comment]
Oh yes, I just got this error today https://paste.gg/p/anonymous/f0f4cd1ccfdd46298352860d293f399f/files/d419c09077764a1db36db8832ac7f58e/raw

no idea whats happening

**Comment by sgdc3** [comment]
seems related with the api issues mojang is experiencing this week

**Comment by sgdc3** [comment]
my guess is that ChangeSkin isn't able to handle 429 errors while fetching skins, and this puts the plugin into an illegal state where the skin UUID is null

**Comment by H4kt** [comment]
Will it be fixed and how long to wait for it?

**Comment by BestMark** [comment]
I have same problem. Please, fix it.

**Comment by games647** [comment]
I added some debug code. It's interesting that the skin id is null whoever the remaining skin could be downloaded.

**Comment by games647** [comment]
>my guess is that ChangeSkin isn't able to handle 429 errors while fetching skins, and this puts the plugin into an illegal state where the skin UUID is null

I just tested it, that doesn't seem to be the cause, because on error the operation would then be aborted. So far I couldn't reproduce it locally. It would be great to have someone report the bug using the new version so I could see the source of this error.

An assumption is that Mojang no longer reports the skin/owner UUID. This would make the UUID null on parsing and cause the NPE during access. The skin could still be valid with a correct signature. This is not the first time Mojang changed the format. In 2018 they changed the order of the reported fields. This change however applied to all new requested skins. This is not the case for this current bug.

So for this purpose ChangeSkin will now log the output retrieved from Mojang. Then I could verify the output. If it's actually still a valid skin, I will add support for this data format although it could be temporarily issue during the issues Mojang servers are having.

>seems related with the api issues mojang is experiencing this week

Currently the status appears to be green again. So it might be fine again?

**Comment by DoNotSpamPls** [comment]
I'd like to add that I have been experiencing this issue when players log in for the first time.

**Comment by games647** [comment]
@DoNotSpamPls I tried that too, but couldn't reproduce it.

**Comment by andramil** [comment]
After update to 225 skin start to work but work oddly. After change skin, players get alex or steave. After /skinupdate they get expected result. After log out they get alex again and had to use /skinupdate one more time.  24 hours after 225 update, there is no problem at all. Works good. Im a confused.
