### ISSUE TITLE
403 for third-party API

### ISSUE THREAD

**Issue by tuanjr** [games647/ChangeSkin#25]
this is error:
http://paste.ubuntu.com/17658899/
when i try to access url https://us.mc-api.net/v3/uuid/Hirita so cloudflare ask me to confirm, are this cause error? my country is Vietnam

**Comment by games647** [comment]
Really you're blocked from Cloudflare?

Oh man, this means the alternative site mcapi.ca is also blocked.

**Comment by tuanjr** [comment]
No, i'm not blocked from cloudflare. Cloudflare just ask me confirm on first time i access  https://us.mc-api.net/v3/uuid/Hirita.

**Comment by games647** [comment]
403 stands for forbidden. Maybe your server got blocked because of the unusual source of the traffic.

Do you still get this error? If not I think you have to solve the captcha from the ip of the server. Maybe tunnel your connection to that server and then access the website.

Can you access one of these without the captcha?

* https://craftapi.com/api/user/uuid/Krymonota  
* https://**eu**.mc-api.net/
* https://mcapi.de/
* https://craftapi.com/user-api

**Comment by tuanjr** [comment]
current (now), access from my pc (not server)
No captch: https://craftapi.com/api/user/uuid/Krymonota
Captcha: https://eu.mc-api.net/
No Captcha: https://mcapi.de/
No Captcha: https://craftapi.com/user-api

**Comment by games647** [comment]
And https://mcapi.ca?

**Comment by tuanjr** [comment]
No captcha: https://mcapi.ca

**Comment by games647** [comment]
I'll ask the owners of us.mc-api.net if they adjust the settings.

**Comment by tuanjr** [comment]
and, what is this?

> [15:46:45] [Server thread/INFO]: [ChangeSkin] Received instant update request from BungeeCord. This request should only be send if the command /setskin was invoked
> [15:46:45] [Server thread/INFO]: [ChangeSkin] Instant update for

**Comment by games647** [comment]
It's a debug message to fix the random skin issue a BungeeCord user has.

**Comment by games647** [comment]
Could you try this version: https://github.com/games647/ChangeSkin/releases/tag/user-agent

**Comment by tuanjr** [comment]
ok, try now

**Comment by tuanjr** [comment]
still not fixed: http://paste.ubuntu.com/17686792/

**Comment by games647** [comment]
I've contacted them.

**Comment by games647** [comment]
Is Hirita a new player?

**Comment by tuanjr** [comment]
i'm not sure, my network current has 400 player online, so not sure she is new, or old.
But This error spam bungeecord console, are you want i send you full log of bungeecord?

**Comment by games647** [comment]
Here is a version which accesses the mc-api.de

https://github.com/games647/ChangeSkin/releases/tag/mc-api-de

**Comment by tuanjr** [comment]
in mc-api-de version:
don't has 403 error but has this error:
http://paste.ubuntu.com/17735246/

**Comment by games647** [comment]
Next try with craftapi

https://github.com/games647/ChangeSkin/releases/tag/craftapi

**Comment by tuanjr** [comment]
when i try version: https://github.com/games647/ChangeSkin/releases/tag/fix-limit
403 and other error in this topic seem to be fixed, but this error is come back: https://github.com/games647/ChangeSkin/issues/22

**Comment by games647** [comment]
You should try the crafapi one. It''s separated into different branches

**Comment by tuanjr** [comment]
@games647  try craft api and has this error: http://paste.ubuntu.com/17782256/

**Comment by games647** [comment]
Does this happen immediately or after a few times.

**Comment by tuanjr** [comment]
i dont understand what your mean!?
But with my network 400 player online, every 30 second, above error appear in bungeecord.

**Comment by tuanjr** [comment]
i think every time player access to network.

**Comment by games647** [comment]
I move back to us.mc-api.net as they said they fixed it.

**Comment by tuanjr** [comment]
i see plugin SkinRestorer use: mcapi.ca, and i never have issues.

**Comment by games647** [comment]
The issue in mcapi.ca is that they have big rate-limiting issues which where the ChangeSkin would receive a response as the player is cracked.

**Comment by tuanjr** [comment]
@games647 
with popular skin like "Notch".../skin skin-name work, but many skin won't work, like "quicksilver", "QuicksilverDC"....
i find skin name (premium name) from this website: mcskinsearch.com
when i use plugin SkinRestorer, all skin from this website work fine!

**Comment by games647** [comment]
>with popular skin like "Notch".../skin skin-name work, but many skin (not popular) won't work, like "quicksilver", "QuicksilverDC"....

Because the Notch name is cached. I tried mcapi.ca with another user and worked only for a few skins. Every other response return a cracked response. This is very error-prone, because you should response a clear error when the server hits a rate-limit.

**Comment by tuanjr** [comment]
what is rate limit? number of skins is allowed to download on 1 minutes? how i can fix it rate limit?
or how to fix this issues?
my english very, sorry, i'm try to understand what your meant.

**Comment by games647** [comment]
Mojang limits the number API requests we can make. There are tons of services like mcapi.ca, us.mc-api.net ... to workaround this caching the same requests for multiple requests. If the request isn't cached **they** will make requests the requests to Mojang. The rate-limit is IPv4 wide. mcapi.ca uses for example multiple IPv4-addresses to still make requests to Mojang, because they will possible hit the limit faster if they do that for other servers too.

The rate-limit for:
name->uuid conversions is by 600 requests per minute and each request can contain up to 100 usernames. 
uuid->skin same user one minute

The problem is that plugins like ChangeSkin and SkinRestorer need the UUID and because the server is in offline mode, we have to ask the Mojang API for it.

**Comment by tuanjr** [comment]
is it mean that i can't fix anything? only wait for you fix it?

**Comment by games647** [comment]
I contacted the owner of mcapi.ca to make it possible to use both services. Example: Check mcapi.ca first and then us.mc-api.net.

**Comment by games647** [comment]
The author of mcapi.ca replied that he will implement the requested changes and says that he also improved the caching mechanism. I already experienced that it worked better as before. 

So I might switch to mcapi.ca nad use us.mc-api.net as backup solution. 

Why? Because the owner of mcapi.ca will make changes to make it clear that if a user is cracked or just the fetch failed.

**Comment by games647** [comment]
And now us.mc-api.net is hitting a lot rate-limits.

**Comment by games647** [comment]
If you didn't noticed I'm completely switching to mcapi.ca (https://github.com/games647/ChangeSkin/commit/d8e1ce9e17f892c89574ef455ce884c71e499c99) as primary third-party api.

**Comment by games647** [comment]
If that will fail, I'm using us.mc-api.net as backup solution.
