### ISSUE TITLE
Whitelist and Blacklist

### ISSUE THREAD

**Issue by andramil** [games647/ChangeSkin#87]
Hi, 
I wanted to set blacklist on my BungeeCord server but BungeeCord doesn't support wildcard permissions.
How can I blacklist some skins?

**Comment by games647** [comment]
That could work in BungeeCord, because I wrote some workaround it.

https://github.com/games647/ChangeSkin/blob/d80dffd9bb246b7a8aa06b726cba65a8d105c9fb/bungee/src/main/java/com/github/games647/changeskin/bungee/ChangeSkinBungee.java#L255-L263

This checks for the wildcard permission and performs another check for the negative permission.

**Comment by andramil** [comment]
With:
`bukkit-permissions: true`
They have to have both 
`changeskin.command.setskin`
on bungeecord permissions and bukkit permissions. 
If i set blacklist and give them 
```
  - changeskin.skin.whitelist.*
  - -changeskin.skin.whitelist.8c4c8312-e8d1-4c0d-a132-f206409c8f24
  - -changeskin.skin.whitelist.7573a14e-fd2e-43bf-89b6-6391fc0e9f70
  - -changeskin.skin.whitelist.456bbc85-2dc8-44df-a741-850ea9ecc004
  - -changeskin.skin.whitelist.f1232e8a-991d-4bd7-bda5-033b34ab994b
```
on bungeecord, do I have to give this same on bukkit?
If not - its not working. If yes, I will check at night.

**Comment by games647** [comment]
With bukkit-permissions enabled, you should give the players the full permission on BungeeCord and the actual check will performed on Bukkit.

**Comment by andramil** [comment]
Forgot about this topic. 
WL and BL working great ;)

**Comment by games647** [comment]
Thanks for the response.
