### ISSUE TITLE
How to download skins?

### ISSUE THREAD

**Issue by jakovkacan** [games647/ChangeSkin#89]
I wanted to download one skin that I used for a long time on the server. I went to Google and searched for "Minecraft Skin Downloader" and I entered skin name that I used but the page showed completely different skin. I tried to find other pages but still did not find the skin I wanted. Then I went to ChangeSkin Database, went to "skinData" collum and found a name with the skin I wanted. Then I found "SkinURL" and I have a question. How to use that URL to download my skin?

**Comment by games647** [comment]
Previously it was possible to choose the SkinURL on your own, so you could host the skin anywhere, but this lead to privacy issues, so Mojang removed that and now every skin have to be signed by them. This means that you have to find someone that have this skin and download it using `/skin <name>`. ChangeSkin saves this response to the local database. Even if that player changes the skin to something else you still keep the skin, because it's locally saved. 

The SkinURL you found is the source where the client will download the image from. The same image will always get stored on the same location. If someone uploads a new skin on their account it will be stored on a different location. 

You can also temporarily upload a skin to Mojang, let ChangeSkin download the new signed skin data and then revert to the old one (ChangeSkin can do this automatically). Although the skin is no longer associated to the Mojang account, we have the signed skin data and so could use the same skin that was temporarily uploaded.

**Comment by jakovkacan** [comment]
So can I download it then or...?

**Comment by games647** [comment]
Yes either if they are signed (for example from: https://mineskin.org) or in use at the moment you want to download it.

**Comment by jakovkacan** [comment]
I Just paste link there?

**Comment by games647** [comment]
No base64 decode the values and put them into the database. I'm working on a ways to directly do it by command, but the API of mineskin is not documented.

**Comment by jakovkacan** [comment]
So I need to wait for the update?

**Comment by games647** [comment]
Or just copy it into the database

**Comment by jakovkacan** [comment]
Copy what?

**Comment by games647** [comment]
The base64 decoded data from the mineskin website if you click on one of the heads.

**Comment by jakovkacan** [comment]
I just scrolled thru Mineskin and entered some random username. Then site
showed "Texture Valute" "Texture Signature" and "Texture URL". The URL was
http://textures.minecraft.net/Texture/(random numbers). I replaced the
random numbers with SkinURL found in database on my server and I finnaly
got skin file...

**Comment by ziceptor** [comment]
https://github.com/MineSkin/api.mineskin.org
